name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  call-deploy-app:
    uses: ./.github/workflows/deploy-app.yml
    with:
      service-name: trassenscout-production
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DATABASE_URL:  ${{ secrets.DATABASE_URL_PRODUCTION }}
      SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY_PRODUCTION }}
